namespace: staging

gateway:
  image: fati1707/k-api-gateway
  tag: latest
  port: 8000
  replicas: 2

orders:
  image: fati1707/k-api-orders
  tag: latest
  port: 8001
  replicas: 2

users:
  image: fati1707/k-api-users
  tag: latest
  port: 8002
  replicas: 2

